name: Notify Slack on Pull Request

on:
  pull_request:
    types:
      - labeled

jobs:
  conditional-job:
    if: ${{ contains(join(fromJson(github.event.pull_request.labels | toJSON).name, ','), 'run-workflow') }}
    runs-on: ubuntu-latest
    steps:
      - name: Setting env
        id: set-env
        run: |
          labels=$(jq -r '.pull_request.labels[].name' <<< "${{ toJSON(github.event) }}")
          if [[ "$labels" == *"run-workflow"* ]]; then
              echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
          elif [[ "$labels" == *"run-something-else"* ]]; then
              echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
          else
              echo "Error: Ninguna etiqueta coincide. SLACK_WEBHOOK no será configurado."
              exit 1
          fi
      - name: Send Slack Notification with curl
        run: |
          if [[ -z "$SLACK_WEBHOOK" ]]; then
              echo "Error: SLACK_WEBHOOK no está configurado."
              exit 1
          fi

          curl -X POST -H 'Content-type: application/json' \
          --data "$(cat <<EOF
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New PR Created :rocket:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*User:*\n${{ github.actor }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\nPull Request\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Title:*\n${{ github.event.pull_request.title }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ github.head_ref }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.head.sha }}>\n"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "See Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}",
                    "style": "primary"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Powered by Innovación Gascaribe"
                  }
                ]
              }
            ]
          }
          EOF
          )" \
          $SLACK_WEBHOOK
