name: Notify Slack on Pull Request

on:
  pull_request:
    types:
      - labeled

jobs:
  conditional-job:
    if: contains(github.event.pull_request.labels.*.name, 'run-workflow') # Verifica si la etiqueta existe
    runs-on: ubuntu-latest
    steps:
      - name: Setting env 
        id: set-env
        run: |
          LABELS=$(jq -r '.pull_request.labels[].name' < $GITHUB_EVENT_PATH)
          if echo "$LABELS" | grep -q "run-workflow"; then
            echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
          elif echo "$LABELS" | grep -q "run-something-else"; then
            echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
          else
            echo "Error: Ninguna etiqueta coincide. SLACK_WEBHOOK no será configurado."
            exit 1
          fi
              - name: Check out code
        uses: actions/checkout@v3

      - name: Get all PR labels
        id: get-labels
        run: |
          # Usa la API de GitHub para obtener todas las etiquetas del PR
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          REPO=${{ github.repository }}
          LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels" | jq -r '.[].name')
          
          echo "PR_LABELS=$LABELS" >> $GITHUB_ENV
          echo "Labels: $LABELS"

      - name: Set environment variables based on labels
        id: set-env
        run: |
          DEPLOY_ENV="development" # Valor por defecto
          for label in $PR_LABELS; do
            if [[ "$label" == "run-workflow" ]]; then
              SLACK_WEBHOOK="production"
            elif [[ "$label" == "run-workflow" ]]; then
              SLACK_WEBHOOK="staging"
            fi
          done

          echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_ENV



      - name: Get PR labels
        id: get_labels
        run: |
          PR_LABELS="${{ github.event.pull_request.labels }}"
          echo "PR Labels: $PR_LABELS"
        
      - name: Set environment variable based on labels
        id: set_env_var
        run: |
          PR_LABELS="${{ github.event.pull_request.labels }}"
          LABEL=0  # Default value if no labels match

          # Check for label1 or label2
          if [[ "$PR_LABELS" == *"run-workflow"* ]]; then
            LABEL="${{ secrets.SLACK_WEBHOOK_URL }}"
          elif [[ "$PR_LABELS" == *"run-workflow"* ]]; then
            LABEL="${{ secrets.SLACK_WEBHOOK_URL }}"
          fi

          # Export the environment variable
          echo "LABEL=$LABEL" >> $GITHUB_ENV

      - name: Display environment variable
        run: echo "The value of LABEL is ${{ env.LABEL }}"