name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification with curl
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": "A new Pull Request has been created by *${{ github.actor }}* :rocket:",
              "attachments": [
                {
                  "color": "#36a64f",
                  "title": "Pull Request Details",
                  "title_link": "${{ github.event.pull_request.html_url }}",
                  "fields": [
                    {
                      "title": "Title",
                      "value": "${{ github.event.pull_request.title }}",
                      "short": true
                    },
                    {
                      "title": "Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    }
                  ]
                }
              ]
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}