name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        with:
          payload: |
            {
              "text": "A new Pull Request has been created by *${{ github.actor }}* :rocket: \n*Title*: ${{ github.event.pull_request.title }} \n*URL*: <${{ github.event.pull_request.html_url }}>",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":bell: *New Pull Request Created*"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Title*: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}> \n*URL*: <${{ github.event.pull_request.html_url }}> \n*Author*: ${{ github.actor }}"
                  }
                }
              ]
            }
