name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification with curl
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "GitHub PR Notifications"
                  }
                },
                "type": "section",
                "fields" : [
                 {
                 "type": "mrkdwn",
                 "text": "*User:*\n${{ github.actor }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Event:*\nPull Request"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Ref:*\n${{ github.ref }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Branch:*\n${{ github.head_ref }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Repository:*\n${{ github.repository }}"
                },
                {
                  "type": "mrkdwn",
                  "text": "*Commit:*\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.head.sha }}>"
                },
                {
                  "type": "mrkdwn",
                  "text": "*PR URL:*\n<${{ github.event.pull_request.html_url }}>"
                }
              ]
            }' \
            ${{ secrets.SLACK_WEBHOOK_URL }}