name: Notify Slack on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification with curl
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "New PR Created :rocket:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*User:*\n${{ github.actor }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Event:*\nPull Request\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Ref:*\n${{ github.ref }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Branch:*\n${{ github.head_ref }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n${{ github.repository }}\n"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Commit:*\n<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.head.sha }}>\n"
                  }
                ]
              },
              {
                "type": "actions",
                "elements": [
                  {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Ver Pull Request"
                    },
                    "url": "${{ github.event.pull_request.html_url }}",
                    "style": "primary"
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "mrkdwn",
                    "text": "Triggered on this workflow run | Innovación Gascaribe"
                  }
                ]
              }
            ]
          }' \
          $SLACK_WEBHOOK